### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by muschellij2** [MRKonrad/tomato#8]
Looks like an interesting suite of tools!  Do you have installation/build instructions or should you just use one of the releases?  I think it'd be good to include this in the README.

**Comment by MRKonrad** [comment]
Thanks for the suggestion John! 
I have added a short paragraph to the README.
In the future I plan to deploy user friendly build scripts.

**Comment by MRKonrad** [comment]
I have wrote user manual with a tutorial here: https://mrkonrad.github.io/tomato_docs/
Thanks again for the suggestion!
